### ISSUE TITLE
getting error ChatHistory is too long to get a completion. Try reducing the available functions.

### ISSUE THREAD

**Issue by Naveen-Reddy237** [Azure/semantic-kernel-bot-in-a-box#3]
Hi,

I'm getting this error ChatHistory is too long to get a completion. Try reducing the available functions. 

could you please advise, Thanks

**Comment by MarcoABCardoso** [comment]
Hello Naveen! Thank you for your interest in the project.

I have some code in progress to configure the number of chat history messages to keep in context. This should help address context size issues.

Could you provide some more details about your issue? Does it happen after multiple conversation turns, or after a particularly large prompt?

**Comment by Naveen-Reddy237** [comment]
Thanks for your response.

It happens after multiple conversation turns.

**Comment by MarcoABCardoso** [comment]
Perfect, that is currently being worked on and should have a fix by today.
I will link the commit to this issue when the change goes through.

**Comment by Naveen-Reddy237** [comment]
ok Thank you

**Comment by MarcoABCardoso** [comment]
A fix has been pushed, with a corresponding configuration CONVERSATION_HISTORY_MAX_MESSAGES. This should fix your original issue.

Regarding the UploadPlugin, PDF files should be the only type supported by default. If those are not working for you, please feel free to open a new issue with more details.

**Comment by Naveen-Reddy237** [comment]
Hi @MarcoABCardoso 

I have imported two functions like below
kernel.ImportFunctions(new KBSearchPlugin(_config, conversationData), "KBSearchPlugin");
kernel.ImportFunctions(new SearchPlugin(_config, conversationData), "SearchPlugin");

it is generating observations in the response but at the end instead of final Answer it is giving error ChatHistory is too long to get a completion. Try reducing the available functions. 

could you please advise, Thanks
