### ISSUE TITLE
Any plans to update to the latest version of Semantic Kernel. 

### ISSUE THREAD

**Issue by Netizine** [Azure/semantic-kernel-bot-in-a-box#8]
A lot of the functionality like Planners, is removed now

**Comment by MarcoABCardoso** [comment]
Hello @Netizine !

Yes, we're planning on updating this repository with the official v1.0 of Semantic Kernel as soon as it's released in the next few weeks.

We're currently working on the breaking changes for the RC version and plan to support either the FunctionCallingStepwisePlanner or the HandlebarsPlanner, which have been appointed as the next generation of Planners.

Marco

**Comment by Netizine** [comment]
@MarcoABCardoso Thats fantastic news. You cover support for the one thing I feel is missing in any LLM model. The ability to render content beyond text and markdown. I see a lot of potential in using Adative Cards with Semantic Kernel and the Bot Framework. The great news of course is you guys have 1.0.1 out https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-1.0.1
